b''
b''
b''
Dataset generated
resetted state: [1 4]
[0, 0.3]
action: [0, 0.3]
{'allowed': [0], 'infected': [45]}
[0, 0.3]
action: [0, 0.3]
{'allowed': [0], 'infected': [7]}
[0, 0.3]
action: [0, 0.3]
{'allowed': [0], 'infected': [5]}
[0, 0.3]
action: [0, 0.3]
{'allowed': [0], 'infected': [6]}
[50, 0.3]
action: [50, 0.3]
{'allowed': [50], 'infected': [4]}
[50, 0.3]
action: [50, 0.3]
{'allowed': [50], 'infected': [8]}
[50, 0.3]
action: [50, 0.3]
{'allowed': [50], 'infected': [4]}
[50, 0.3]
action: [50, 0.3]
{'allowed': [50], 'infected': [8]}
[50, 0.3]
action: [50, 0.3]
{'allowed': [50], 'infected': [0]}
[50, 0.3]
action: [50, 0.3]
{'allowed': [50], 'infected': [0]}
[50, 0.3]
action: [50, 0.3]
{'allowed': [50], 'infected': [0]}
[50, 0.3]
action: [50, 0.3]
{'allowed': [50], 'infected': [0]}
[50, 0.3]
action: [50, 0.3]
{'allowed': [50], 'infected': [0]}
[50, 0.3]
action: [50, 0.3]
{'allowed': [50], 'infected': [0]}
[0, 0.3]
action: [0, 0.3]
{'allowed': [0], 'infected': [0]}
Total Episode reward: 90
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.92it/s]
Traceback (most recent call last):
  File "main.py", line 104, in <module>
    os.chdir("results")
FileNotFoundError: [Errno 2] No such file or directory: 'results'